---
title: "SMA Project"
author: "Basile Demaret"
date: "20 novembre 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r pressure, echo=FALSE}



datafoot <- read.csv("results.csv",header = TRUE, dec=".",sep=",")
datafoot
summary(datafoot)

n = nrow(data2)
split = sample(c(TRUE, FALSE), n, replace=TRUE, prob=c(0.75, 0.25))
```

```{r pressure, echo=FALSE}
library(rockchalk)
library(plyr)



data2 <- datafoot[-1]
gameresult=c()

for (i in 1:length(data2$home_score)){
  if (data2$home_score[i]>data2$away_score[i]){gameresult[i]=1}
  else if(data2$home_score[i]==data2$away_score[i]){gameresult[i]=0}
  else{gameresult[i]=2}
}

data2 <- cbind(data2,gameresult)



```


```{r pressure, echo=FALSE}

levels(data2$home_team)<- cbind(levels(data2$home_team),"Other")
##4 times :
for (i in 1:320){
  if (table(data2$home_team)[i]<300) {
    data2$home_team <- combineLevels(data2$home_team,levs = c("Other", names(table(data2$home_team)[i])), newLabel = c("Other") )
  }
}

levels(data2$home_team)


levels(data2$away_team)<- cbind(levels(data2$away_team),"Other")
##4 times :
for (i in 1:307){
  if (table(data2$away_team)[i]<300) {
    data2$away_team <- combineLevels(data2$away_team,levs = c("Other", names(table(data2$away_team)[i])), newLabel = c("Other") )
  }
}

levels(data2$away_team)

levels(data2$tournament)<- cbind(levels(data2$tournament),"Other")
##2 times
for (i in 1:112){
  if (table(data2$tournament)[i]<80) {
    data2$tournament <- combineLevels(data2$tournament,levs = c("Other", names(table(data2$tournament)[i])), newLabel = c("Other") )
  }
}

levels(data2$tournament)



levels(data2$country)<- cbind(levels(data2$country),"Other")
##4 times
for (i in 1:266){
  if (table(data2$country)[i]<300) {
    data2$country <- combineLevels(data2$country,levs = c("Other", names(table(data2$country)[i])), newLabel = c("Other") )
  }
}

levels(data2$country)

summary(data2)

data2$gameresult<- as.factor(data2$gameresult)


###write.csv(data2, file = "DATA2.csv")

```

```{r pressure, echo=FALSE}

data2  <- read.csv("DATA2.csv",header = TRUE, dec=".",sep=",")
data2<-data2[-1]
data2<- data2[-6]
data2<- data2[-3]
data2<- data2[-3]




training = data2[split, ]
testing = data2[!split, ]
```


```{r pressure, echo=FALSE}
###RandomForest  1




library(randomForest)


rf <- randomForest(formula=gameresult ~ ., data=training,ntree=250,mtry=1,na.action=na.omit)
rf
Gpredict = predict(rf, newdata=testing)

Init=testing$gameresult

cm = table(Init, Gpredict)

cm

ok=0
for (i in 1:3){
  ok=cm[i,i]+ok
}
acc=ok/length(testing$gameresult)
```

```{r pressure, echo=FALSE}
###RandomForest opt
library(randomForest)


rf <- randomForest(formula=gameresult ~ ., data=training,ntree=500,mtry=2,na.action=na.omit)
rf


Gpredict = predict(rf, newdata=testing)

Init=testing$gameresult

cm = table(Init, Gpredict)
cm

ok=0
for (i in 1:3){
  ok=cm[i,i]+ok
}
acc=ok/length(testing$gameresult)
```

```{r pressure, echo=FALSE}
###K-NN
library(class)

data3  <- datafoot

gameresult=c()

for (i in 1:length(data3$home_score)){
  if (data3$home_score[i]>data3$away_score[i]){gameresult[i]=1}
  else if(data3$home_score[i]==data3$away_score[i]){gameresult[i]=0}
  else{gameresult[i]=2}
}

data3 <- cbind(data3,gameresult)


data3<-data3[-1]
data3<-data3[-3]
data3<-data3[-3]

data3$home_team<-as.numeric(data3$home_team)
data3$away_team<-as.numeric(data3$away_team)
data3$tournament<-as.numeric(data3$tournament)
data3$country<-as.numeric(data3$country)
data3$city<-as.numeric(data3$city)
data3$neutral<-as.numeric(data3$neutral)
data3$gameresult<-as.numeric(data3$gameresult)

training2 = data3[split, ]
testing2 = data3[!split, ]

gameresultO<- training2[,7]



pr <- kNN(gameresult~.,train=training2,test=testing2,norm=T,k=10)

cm = table(testing2$gameresult, pr)
cm

ok=0
for (i in 1:3){
  ok=cm[i,i]+ok
}
acc=ok/length(testing2$gameresult)
acc
```


```{r pressure, echo=FALSE}
pr2 <- kNN(gameresult~.,train=training2,test=testing2,norm=T,k=30)

cm2 = table(testing2$gameresult, pr2)
cm2

ok=0
for (i in 1:3){
  ok=cm2[i,i]+ok
}
acc2=ok/length(testing2$gameresult)
acc2
```